routes/web.php
<?php

use App\Models\Role;
use App\Models\Permission;
use App\Models\User;
use App\Models\Setting;
use App\Models\Log;
use App\Models\Vehicle;
use App\Models\House;
use App\Models\Type;
use App\Models\Family;
use App\Models\FamilyPerson;
use App\Models\Camera;
use App\Models\VCompany;
use App\Models\VModel;

Auth::routes();

//auto redirect tp dashboard.....

Route::get('/', function () {

    return redirect('/dashboard/');

})->middleware('maintenance');

Route::group(['prefix' => '/dashboard', 'middleware' => ['maintenance']], function () {


    /* Country state city village dependent Drop Downs*/

    Route::resource('location', 'Location\HomeController');
    Route::resource('location-countries', 'Location\CountryController');
    Route::resource('location-states', 'Location\StateController');
    Route::resource('location-districts', 'Location\DistrictController');
    Route::resource('location-cities', 'Location\CityController');
    Route::resource('location-tehsils', 'Location\TehsilController');
    Route::resource('location-colonies', 'Location\ColonyController');

    /*Message Modules*/

    Route::resource('messages', 'MessageController');

    /*LRM (Land Record Management System*/

    Route::resource('lrm', 'LRM\HomeController');
    Route::resource('lrm-ministry', 'LRM\MinistryController');
    Route::resource('lrm-organization', 'LRM\OrganizationController');
    Route::resource('lrm-department', 'LRM\DepartmentController');
    Route::resource('lrm-rank', 'LRM\RankController');
    Route::resource('lrm-grade', 'LRM\GradeController');
    Route::resource('lrm-qualification', 'LRM\QualificationController');
    Route::resource('lrm-profession', 'LRM\ProfessionController');
    Route::resource('lrm-wing', 'LRM\WingController');
    Route::resource('lrm-settings', 'LRM\SettingController');
    /* Now ready to create Forms*/
    Route::resource('lrm-application', 'LRM\Form\ApplicationController');

    /*Device */

    Route::resource('device', 'Device\HomeController');
    Route::resource('device-class', 'Device\ClassController');
    Route::resource('device-operatingsystem', 'Device\DOperatingSystemController');
    Route::resource('device-make', 'Device\MakeController');
    Route::resource('device-model', 'Device\ModelController');
    Route::resource('device-type', 'Device\TypeController');

    /*VRS*/

    Route::resource('vrs', 'VRS\HomeController');
    Route::resource('vrs-vehicles', 'VRS\VehicleController');
    Route::resource('vrs-vehicle-types', 'VRS\VehicleTypeController');
    Route::resource('vrs-vehicle-companies', 'VRS\VehicleCompanyController');
    Route::resource('vrs-vehicle-models', 'VRS\VehicleModelController');
    Route::resource('vrs-vehicle-nature', 'VRS\VehicleNatureController');

    /*HRM*/

    Route::resource('hrm', 'HRM\HomeController');
    Route::resource('hrm-departments', 'HRM\DepartmentController');
    Route::resource('hrm-designations', 'HRM\DesignationController');
    Route::resource('hrm-employers', 'HRM\EmployerController');
    Route::resource('hrm-emp-types', 'HRM\EmployeeTypeController');
    Route::resource('hrm-card-types', 'HRM\CardTypeController');
    Route::resource('hrm-relations', 'HRM\RelationController');

    /*....Society Phases and Gates....*/

    Route::resource('society-gates', 'Society\GateController');
    Route::resource('society-booths', 'Society\BoothController');
    Route::resource('society-phase-gate-locations', 'Society\LocationController');


    /*visitor companies*/

    Route::resource('vcompanies', 'Vehicle\CompanyController');

    /*visitor models*/

    Route::resource('vmodels', 'Vehicle\ModelController');

    Route::get('', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);

    Route::get('system/apply/status/{type}/{id}/{value}', ['as' => 'system.apply.status', 'uses' => 'System\AjaxController@apply_status']);
    //Load more routes
    Route::get('system/load/more/{type}', ['as' => 'system.load.more', 'uses' => 'System\AjaxController@load_more']);
    //System Assigning routes
    Route::post('system/assign', ['as' => 'system.assign', 'uses' => 'System\AjaxController@assign']);

    Route::get('till', ['as' => 'till', 'uses' => 'TillController@index',
        'permissions' => User::modulePermissions(true, 'read')]);
    Route::get('tills/logs', ['as' => 'tills.logs', 'uses' => 'TillController@logs']);
    Route::get('till/manage', ['as' => 'till.manage', 'uses' => 'TillController@index',
        'permissions' => \App\Models\Booth::modulePermissions(true, 'read')]);

    //Settings

    Route::get('settings', ['as' => 'settings', 'uses' => 'SettingController@index',
        'permissions' => Setting::modulePermissions(true, 'read')]);
    Route::put('settings/update/{id}', ['as' => 'settings.update', 'uses' => 'SettingController@update',
        'permissions' => Setting::modulePermissions(true, 'edit')]);

    //Logs

    Route::get('logs/{type?}', ['as' => 'logs', 'uses' => 'LogController@index',
        'permissions' => Log::modulePermissions(true, 'read')]);

    //Applying status
    Route::get('system/apply/status/{type}/{id}/{value}', ['as' => 'system.apply.status', 'uses' => 'System\AjaxController@apply_status']);
    //Load more routes
    Route::get('system/load/more/{type}', ['as' => 'system.load.more', 'uses' => 'System\AjaxController@load_more']);
    //System Assigning routes
    Route::post('system/assign', ['as' => 'system.assign', 'uses' => 'System\AjaxController@assign']);


    // List of all Notifications

    Route::get('booth-notifications-count', 'BoothController@countNotifications')->name('booth-notifications-count');
    Route::get('booth-notifications/{for}/{type}/{boothId}', 'BoothController@getNotifications')->name('booth-notifications');
    Route::post('booth-read-notifications', 'BoothController@markAsReadNotifications')->name('booth-read-notifications');
    Route::get('booth-visitor-logs/{boothId}', 'BoothController@visitorLog')->name('booth-visitor-logs');
    Route::get('booth-cameras/{boothId}', 'BoothController@boothCameras')->name('booth-cameras');
    Route::get('booth-images/{boothId}', 'BoothController@boothImages')->name('booth-images');
    // Manage Visitor

    Route::resource('visitors', 'VisitorController');

});


Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\LoginController@logout']);
Route::get('lang/{locale}', 'SwitcherController@lang')->name('lang.switcher')->middleware('maintenance');
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login')->middleware('maintenance');
Route::post('customLogin', 'Auth\LoginController@customLogin')->name('customLogin')->middleware('maintenance');
Route::post('customBoothLogin', 'Auth\BoothController@customBoothLogin')->name('customBoothLogin');
Route::get('boothLogin', 'Auth\BoothController@login')->name('booth.login');
Route::get('/till/filter', 'TillController@filter')->name('till.filter');
Route::get('/logs/visitor/set', 'LogController@save_visitor_logs')->name('till.filter');
Route::post('till/visitor/save', 'TillController@save_visitor')->name('till.visitor.save');
Route::post('/till/visitor/logs', 'VisitorController@save_logs')->name('till.visitor.save');
Route::post('/dependent/dropdown', 'DropDownController@filter');
Route::get('booth', 'BoothController@manage')->name('booth.manage')->middleware('boothLogin');


Route::post('booth/logout', 'Auth\BoothController@logout')->name('booth.logout');

Route::post('booth/visitors/enter', 'BoothController@enter')->name('booth-enter-visitor');
Route::post('booth/visitors/exit', 'BoothController@exit')->name('booth-exit-visitor');
Route::get('booth/visitor-already-enter-not-exit', 'BoothController@alreadyEnterNotExit')->name('visitor-already-enter-not-exit');
Route::post('booth/visitor/check/exit', 'BoothController@checkVisitorAtExit')->name('booth-check-visitor-at-exit');
Route::post('booth/visitor/check/enter', 'BoothController@checkVisitorAtEnter')->name('booth-check-visitor-at-enter');
Route::post('gen/veh/types', 'GenerationController@vehicleTypes')->name('gen-vehicle-types');
Route::post('gen/veh/companies', 'GenerationController@vehicleCompanies')->name('gen-vehicle-companies');
Route::post('gen/veh/models', 'GenerationController@vehicleModels')->name('gen-vehicle-models');
Route::post('gen/veh/nature/material', 'GenerationController@vehicleMaterialNature')->name('gen-vehicle-nature-of-materials');
Route::post('booth/temp/pic', 'BoothController@getTempPics')->name('booth.temp.pic');
Route::post('booth/temp/pic/all', 'BoothController@getAllTempPics')->name('booth.temp.pic.all');


Route::post('generate_hrm_employee_type_with_ajax', 'HRM\EmployeeTypeController@generate_with_ajax');
Route::post('generate_hrm_employer_with_ajax', 'HRM\EmployerController@generate_with_ajax');
Route::post('generate_hrm_department_with_ajax', 'HRM\DepartmentController@generate_with_ajax');
Route::post('generate_hrm_designation_with_ajax', 'HRM\DesignationController@generate_with_ajax');
Route::post('generate_hrm_card_type_with_ajax', 'HRM\CardTypeController@generate_with_ajax');

Route::post('generate_relation_in_english_with_ajax', 'HRM\RelationController@generate_relation_in_english_with_ajax');
Route::post('generate_relation_in_urdu_with_ajax', 'HRM\RelationController@generate_relation_in_urdu_with_ajax');

app/Models/LRM.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Interfaces\Permissions;
use Illuminate\Database\Eloquent\SoftDeletes;

class LRM extends Model implements Permissions
{

    use SoftDeletes;

    public static function modulePermissions($middleware = false, $route = null)
    {
        if ($middleware) {

            switch ($route) {
                case 'read':
                    return array('read_land_record_form');
                    break;
                case 'create':
                case 'store':
                    return array('create_land_record_form');
                    break;
                case 'edit':
                case 'update':
                    return array('edit_land_record_form');
                    break;
                case 'delete':
                    return array('delete_land_record_form');
                    break;
                default:
                    return array();
            }

        }

        return array(
            'read_land_record_form',
            'create_land_record_form',
            'edit_land_record_form',
            'delete_land_record_form',
        );
    }
}

app/Http/Controllers/LRM/DepartmentController.php
<?php

namespace App\Http\Controllers\LRM;

use App\Http\Controllers\Controller;
use App\Models\Employer;
use App\Models\LRMDepartment;
use App\Models\LRMOrganization;
use App\Models\Type;
use App\Repositories\CurdRepository;
use Carbon\Carbon;
use Illuminate\Http\Request;

class DepartmentController extends Controller
{
    protected $model;

    public function __construct(LRMDepartment $LRMDepartment)
    {
        $this->middleware('auth');
        // set the model
        $this->model = new CurdRepository($LRMDepartment);
    }

    public function index(Request $request)
    {
        $this->authorize('read', LRMDepartment::class);
        $data = $this->model->all($request->all());
        $pageTitle = __('lrm.departments.all_types');
        $viewParams = [
            'pageTitle' => $pageTitle,
            'data' => $data->paginate(20)
        ];
        return view('lrm.department.index', $viewParams);
    }

    public function create(Request $request)
    {
        $this->authorize('create', LRMDepartment::class);
        $types = Type::whereParent('employment')
            ->whereIn('name', ["Government","Private Establishment"])->pluck('name', 'id');
        $pageTitle = __('lrm.departments.create');
        $viewParams = [
            'pageTitle' => $pageTitle,
            'types' => $types
        ];
        return view('lrm.department.create', $viewParams);
    }

    public function store(Request $request)
    {
        $this->authorize('create', LRMDepartment::class);
        $request->validate([
            'name' => 'required|max:255|unique:lrmdepartments,name',
            'name_ur' => 'max:255|unique:lrmdepartments,name_ur',
        ]);
        if ($this->model = $this->model->create($request->only($this->model->getModel()->fillable))) {
            $types = $request->input('types', array());
            if ($types){
                $this->model->types()->sync($types);
            }
            return redirect()->route('lrm-department.index')->with('successMessage', __('lrm.departments.created_success_message'));
        } else {
            return redirect()->back()
                ->withErrors(__('lrm.departments.created_failed'))
                ->withInput();
        }
    }

    public function edit($id)
    {
        $this->authorize('edit', LRMDepartment::class);
        $types = Type::whereParent('employment')
            ->whereIn('name', ["Government","Private Establishment"])->pluck('name', 'id');
        $this->model = $this->model->find($id);
        $pageTitle = __('lrm.edit') ." ". $this->model->name;
        $viewParams = [
            'pageTitle' => $pageTitle,
            'model' => $this->model,
            'types' => $types
        ];
        return view('lrm.department.edit', $viewParams);

    }

    public function update(Request $request,$id)
    {
        $this->authorize('edit', LRMDepartment::class);
        $request->validate([
            'name' => 'required|max:255|unique:lrmdepartments,name,' . $id,
            'name_ur' => 'unique:lrmdepartments,name,' . $id,
        ]);
        $this->model->update($request->only($this->model->getModel()->fillable), $id);
        $this->model = $this->model->find($id);
        if ($this->model) {
            $types = $request->input('types', array());
            if ($types){
                $this->model->types()->sync($types);
            }
            return redirect()->route('lrm-department.index')->with('successMessage', $this->model->name . " " . __('lrm.departments.updated_success_message'));
        }
    }

    public function destroy($id)
    {
        $this->authorize('delete', LRMDepartment::class);
        $this->model = $this->model->find($id);
        $this->model->types()->sync([]);
        if ($this->model->delete()) {
            return redirect()->route('lrm-department.index')->with('errorMessage', $this->model->name . " " . __('lrm.deleted_successfully'));
        }
    }
}

app/Http/Controllers/LRM/Form/ApplicationController.php
<?php

namespace App\Http\Controllers\LRM\FORM;

use App\Http\Controllers\Controller;
use App\Models\LRM;
use Illuminate\Http\Request;

class ApplicationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', LRM::class);
        $pageTitle = __('lrm.application.create');
        $breadcrumbs = [['text' => __('lrm.application.create')]];
        $viewParams = [
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle,
        ];
        return view('lrm.form.application.create', $viewParams);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/LRM/HomeController.php
<?php

namespace App\Http\Controllers\LRM;

use App\Http\Controllers\Controller;
use App\Models\LRM;
use App\Models\Visitor;
use App\Repositories\CurdRepository;
use Illuminate\Http\Request;
use App\Models\VMS;

class HomeController extends Controller
{

    protected $model;

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $this->authorize('read', LRM::class);
        $pageTitle = __('lrm.title');
        $breadcrumbs = [['text' => __('lrm.short_title')]];
        $viewParams = [
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle,
        ];
        return view('lrm.index', $viewParams);
    }
}

resources/views/lrm/rank/create.blade.php
@extends('layouts.colorbox')
@section('pageTitle', $pageTitle)

@section('styleInnerFiles')
    <link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/bootstrap-select/dist/css/bootstrap-select.min.css') }}">
@endsection

@section('content')
    <div class="card card-solid">
        @can('read',\App\Models\LRMRank::class)
            <div class="card-header">
                <div class="card-title">
                    {!! link_to_route('lrm-rank.index',__('lrm.ranks.title'),null,['class'=>'btn btn-info btn-sm']) !!}
                </div>
            </div>
        @endcan
        <div class="card-body pb-0">
            {!! Form::open(['route' => ['lrm-rank.store'], 'method' => 'POST','files' => true]) !!}
            {!! csrf_field() !!}
            <div class="row">
                <div class="form-group col-md-4">
                    {!! Form::label('types', 'Assign Type') !!}
                    {!! Form::select('types[]', $types, null, array('id' => 'type',
                    'class' => 'form-control selectpicker show-menu-arrow', 'data-live-search' => 'true', 'data-selected-text-format' => 'count > 3',
                    'data-size' => '10', 'data-actions-box' => 'true','multiple'=>'multiple')) !!}
                </div>
                <div class="form-group col-md-4">
                    {!! Form::label('inputName', __('lrm.name')) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'autofocus', 'id' => 'inputName' ]) !!}
                    @error('name')
                    <div class="error">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-md-4 form-group text-right">
                    {!! Form::label('inputNameUR',__('lrm.name_ur'),['class'=>'pr-2']) !!}
                    {!! Form::text('name_ur', old('name_ur'), ['class' => 'form-control urduWriter ur','dir'=>'rtl','id' => 'inputNameUR' ]) !!}
                    @error('name_ur')
                    <div class="error">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group text-right col-12">
                    {!! Form::submit(__('lrm.save'), array('class' => 'btn btn-primary btn-sm')) !!}
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@stop
@section('scriptInnerFiles')
    <script src="{{ asset('plugins/keybaord/urdu.js') }}"></script>
    <script type="text/javascript"
            src="{{ asset('plugins/bootstrap-select/dist/js/bootstrap-select.min.js') }}"></script>
@stop

resources/views/lrm/rank/edit.blade.php
@extends('layouts.colorbox')
@section('pageTitle', $pageTitle)

@section('styleInnerFiles')
    <link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/bootstrap-select/dist/css/bootstrap-select.min.css') }}">
@endsection

@section('content')
    <div class="card card-solid">
        @can('read',\App\Models\LRMRank::class)
            <div class="card-header">
                <div class="card-title">
                    {!! link_to_route('lrm-rank.index',__('lrm.ranks.title'),null,['class'=>'btn btn-info btn-sm']) !!}
                </div>
            </div>
        @endcan
        <div class="card-body pb-0">
            {!! Form::model($model, ['route' => ['lrm-rank.update', $model], 'method' => 'PUT','files' => true] ) !!}
            {!! csrf_field() !!}
            <div class="row">
                <div class="form-group col-md-4">
                    {!! Form::label('types', 'Assign Type') !!}
                    {!! Form::select('types[]', $types, null, array('id' => 'type',
                    'class' => 'form-control selectpicker show-menu-arrow', 'data-live-search' => 'true', 'data-selected-text-format' => 'count > 3',
                    'data-size' => '10', 'data-actions-box' => 'true','multiple'=>'multiple')) !!}
                </div>
                <div class="form-group col-md-4">
                    {!! Form::label('inputName', __('lrm.name')) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'autofocus', 'id' => 'inputName' ]) !!}
                    @error('name')
                    <div class="error">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-md-4 form-group text-right">
                    {!! Form::label('inputNameUR',__('lrm.name_ur'),['class'=>'pr-2']) !!}
                    {!! Form::text('name_ur', old('name_ur'), ['class' => 'form-control urduWriter ur','dir'=>'rtl','id' => 'inputNameUR' ]) !!}
                    @error('name_ur')
                    <div class="error">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group text-right col-12">
                    {!! Form::submit(__('lrm.update'), array('class' => 'btn btn-primary btn-sm')) !!}
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@stop
@section('scriptInnerFiles')
    <script src="{{ asset('plugins/keybaord/urdu.js') }}"></script>
    <script type="text/javascript"
            src="{{ asset('plugins/bootstrap-select/dist/js/bootstrap-select.min.js') }}"></script>
@stop
@section('pageScript')
    <script>
        jQuery('input[type=checkbox]').click(function () {
            if ($(this).is(':checked')) {
                $(this).val(1).attr('checked', 'checked');
            } else {
                $(this).val(0).removeAttr('checked');
            }
        });
    </script>
@endsection

resources/views/lrm/rank/index.blade.php
@extends('layouts.colorbox')
@section('pageTitle', $pageTitle)
@section('content')
    <div class="row">
        <div class="col-lg-12 col-12">
            <div class="card">
                <div class="card-header row align-items-center mx-1">
                    <div class="card-title col-xl-6 col-lg-6 col-md-6">
                        @can('create',\App\Models\LRMRank::class)
                            {!! link_to_route('lrm-rank.create',__('system.create'),null,['class'=>'btn bg-gradient-primary btn-sm']) !!}
                        @endcan
                    </div>
                </div>
                <div class="card-body">
                    @include('partials.dashboard.message')
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>{{__('lrm.name')}}</th>
                            <th>{{__('lrm.name_ur')}}</th>
                            <th>{{__('lrm.type')}}</th>
                            <th class="text-center">{{__('lrm.create_date')}}</th>
                            <th class="text-center">{{__('lrm.last_modified')}}</th>
                            <th class="text-center">{{__('lrm.action')}}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(count($data)>0)
                            @foreach($data as $d)
                                <tr>
                                    <td>{{$d->name}}</td>
                                    <td>{{$d->name_ur}}</td>
                                    <td>
                                        <select class="form-control form-control-sm">
                                            @if(count($d->types))
                                                @foreach($d->types as $type)
                                                    <option>{{$type->name}} - {{ $type->name_ur }}</option>
                                                @endforeach
                                            @else
                                                <option>No Type Found</option>
                                            @endif
                                        </select>
                                    </td>
                                    <td class="text-center">{{$d->created_at}}</td>
                                    <td class="text-center">{{$d->updated_at->diffForHumans()}}</td>
                                    <td class="text-center">
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-default">{{__('lrm.action')}}</button>
                                            <button type="button" class="btn btn-default dropdown-toggle"
                                                    data-toggle="dropdown">
                                                <span class="caret"></span>
                                                <span class="sr-only">Toggle Dropdown</span>
                                            </button>
                                            <ul class="dropdown-menu" role="menu">
                                                @can('edit',\App\Models\LRMRank::class)
                                                    <li class="dropdown-item">{!! link_to_route('lrm-rank.edit', __('lrm.edit'), [$d->id]) !!}</li>
                                                @endif
                                                @can('delete',\App\Models\LRMRank::class)
                                                    <form action="{{ route('lrm-rank.destroy',$d->id) }}"
                                                          method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <li class="dropdown-item">
                                                            <button type="submit" class="bg-transparent"
                                                                    onclick="return confirm('Do you really wants to delete this?')"
                                                                    style="border: none;padding-left: 0;color: #c13535;">
                                                                {{__('lrm.delete')}}
                                                            </button>
                                                        </li>
                                                    </form>
                                                @endcan
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr class="text-center">
                                <td colspan="12" class="p-3">No Rank Found</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix">
                    {{ $data->links() }}
                </div>
            </div>
        </div>
    </div>
@stop