routes/web.php
<?php

use App\Models\Role;
use App\Models\Permission;
use App\Models\User;
use App\Models\Setting;
use App\Models\Log;
use App\Models\Vehicle;
use App\Models\House;
use App\Models\Type;
use App\Models\Family;
use App\Models\FamilyPerson;
use App\Models\Camera;
use App\Models\VCompany;
use App\Models\VModel;

Auth::routes();

//auto redirect tp dashboard.....

Route::get('/', function () {

    return redirect('/dashboard/');

})->middleware('maintenance');

Route::group(['prefix' => '/dashboard', 'middleware' => ['maintenance']], function () {


    /* Country state city village dependent Drop Downs*/

    Route::resource('location', 'Location\HomeController');
    Route::resource('location-countries', 'Location\CountryController');
    Route::resource('location-states', 'Location\StateController');
    Route::resource('location-districts', 'Location\DistrictController');
    Route::resource('location-cities', 'Location\CityController');
    Route::resource('location-tehsils', 'Location\TehsilController');
    Route::resource('location-colonies', 'Location\ColonyController');

    /*Message Modules*/

    Route::resource('messages', 'MessageController');

    /*LRM (Land Record Management System*/

    Route::resource('lrm', 'LRM\HomeController');
    Route::resource('lrm-ministry', 'LRM\MinistryController');
    Route::resource('lrm-organization', 'LRM\OrganizationController');
    Route::resource('lrm-department', 'LRM\DepartmentController');
    Route::resource('lrm-rank', 'LRM\RankController');
    Route::resource('lrm-grade', 'LRM\GradeController');
    Route::resource('lrm-qualification', 'LRM\QualificationController');
    Route::resource('lrm-profession', 'LRM\ProfessionController');
    Route::resource('lrm-wing', 'LRM\WingController');
    Route::resource('lrm-settings', 'LRM\SettingController');
    /* Now ready to create Forms*/
    Route::resource('lrm-application', 'LRM\Form\ApplicationController');

    /*Device */

    Route::resource('device', 'Device\HomeController');
    Route::resource('device-class', 'Device\ClassController');
    Route::resource('device-operatingsystem', 'Device\DOperatingSystemController');
    Route::resource('device-make', 'Device\MakeController');
    Route::resource('device-model', 'Device\ModelController');
    Route::resource('device-type', 'Device\TypeController');

    /*VRS*/

    Route::resource('vrs', 'VRS\HomeController');
    Route::resource('vrs-vehicles', 'VRS\VehicleController');
    Route::resource('vrs-vehicle-types', 'VRS\VehicleTypeController');
    Route::resource('vrs-vehicle-companies', 'VRS\VehicleCompanyController');
    Route::resource('vrs-vehicle-models', 'VRS\VehicleModelController');
    Route::resource('vrs-vehicle-nature', 'VRS\VehicleNatureController');

    /*HRM*/

    Route::resource('hrm', 'HRM\HomeController');
    Route::resource('hrm-departments', 'HRM\DepartmentController');
    Route::resource('hrm-designations', 'HRM\DesignationController');
    Route::resource('hrm-employers', 'HRM\EmployerController');
    Route::resource('hrm-emp-types', 'HRM\EmployeeTypeController');
    Route::resource('hrm-card-types', 'HRM\CardTypeController');
    Route::resource('hrm-relations', 'HRM\RelationController');

    /*....Society Phases and Gates....*/

    Route::resource('society-gates', 'Society\GateController');
    Route::resource('society-booths', 'Society\BoothController');
    Route::resource('society-phase-gate-locations', 'Society\LocationController');


    /*visitor companies*/

    Route::resource('vcompanies', 'Vehicle\CompanyController');

    /*visitor models*/

    Route::resource('vmodels', 'Vehicle\ModelController');

    Route::get('', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);

    Route::get('system/apply/status/{type}/{id}/{value}', ['as' => 'system.apply.status', 'uses' => 'System\AjaxController@apply_status']);
    //Load more routes
    Route::get('system/load/more/{type}', ['as' => 'system.load.more', 'uses' => 'System\AjaxController@load_more']);
    //System Assigning routes
    Route::post('system/assign', ['as' => 'system.assign', 'uses' => 'System\AjaxController@assign']);

    Route::get('till', ['as' => 'till', 'uses' => 'TillController@index',
        'permissions' => User::modulePermissions(true, 'read')]);
    Route::get('tills/logs', ['as' => 'tills.logs', 'uses' => 'TillController@logs']);
    Route::get('till/manage', ['as' => 'till.manage', 'uses' => 'TillController@index',
        'permissions' => \App\Models\Booth::modulePermissions(true, 'read')]);

    //Settings

    Route::get('settings', ['as' => 'settings', 'uses' => 'SettingController@index',
        'permissions' => Setting::modulePermissions(true, 'read')]);
    Route::put('settings/update/{id}', ['as' => 'settings.update', 'uses' => 'SettingController@update',
        'permissions' => Setting::modulePermissions(true, 'edit')]);

    //Logs

    Route::get('logs/{type?}', ['as' => 'logs', 'uses' => 'LogController@index',
        'permissions' => Log::modulePermissions(true, 'read')]);

    //Applying status
    Route::get('system/apply/status/{type}/{id}/{value}', ['as' => 'system.apply.status', 'uses' => 'System\AjaxController@apply_status']);
    //Load more routes
    Route::get('system/load/more/{type}', ['as' => 'system.load.more', 'uses' => 'System\AjaxController@load_more']);
    //System Assigning routes
    Route::post('system/assign', ['as' => 'system.assign', 'uses' => 'System\AjaxController@assign']);


    // List of all Notifications

    Route::get('booth-notifications-count', 'BoothController@countNotifications')->name('booth-notifications-count');
    Route::get('booth-notifications/{for}/{type}/{boothId}', 'BoothController@getNotifications')->name('booth-notifications');
    Route::post('booth-read-notifications', 'BoothController@markAsReadNotifications')->name('booth-read-notifications');
    Route::get('booth-visitor-logs/{boothId}', 'BoothController@visitorLog')->name('booth-visitor-logs');
    Route::get('booth-cameras/{boothId}', 'BoothController@boothCameras')->name('booth-cameras');
    Route::get('booth-images/{boothId}', 'BoothController@boothImages')->name('booth-images');
    // Manage Visitor

    Route::resource('visitors', 'VisitorController');

});


Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\LoginController@logout']);
Route::get('lang/{locale}', 'SwitcherController@lang')->name('lang.switcher')->middleware('maintenance');
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login')->middleware('maintenance');
Route::post('customLogin', 'Auth\LoginController@customLogin')->name('customLogin')->middleware('maintenance');
Route::post('customBoothLogin', 'Auth\BoothController@customBoothLogin')->name('customBoothLogin');
Route::get('boothLogin', 'Auth\BoothController@login')->name('booth.login');
Route::get('/till/filter', 'TillController@filter')->name('till.filter');
Route::get('/logs/visitor/set', 'LogController@save_visitor_logs')->name('till.filter');
Route::post('till/visitor/save', 'TillController@save_visitor')->name('till.visitor.save');
Route::post('/till/visitor/logs', 'VisitorController@save_logs')->name('till.visitor.save');
Route::post('/dependent/dropdown', 'DropDownController@filter');
Route::get('booth', 'BoothController@manage')->name('booth.manage')->middleware('boothLogin');


Route::post('booth/logout', 'Auth\BoothController@logout')->name('booth.logout');

Route::post('booth/visitors/enter', 'BoothController@enter')->name('booth-enter-visitor');
Route::post('booth/visitors/exit', 'BoothController@exit')->name('booth-exit-visitor');
Route::get('booth/visitor-already-enter-not-exit', 'BoothController@alreadyEnterNotExit')->name('visitor-already-enter-not-exit');
Route::post('booth/visitor/check/exit', 'BoothController@checkVisitorAtExit')->name('booth-check-visitor-at-exit');
Route::post('booth/visitor/check/enter', 'BoothController@checkVisitorAtEnter')->name('booth-check-visitor-at-enter');
Route::post('gen/veh/types', 'GenerationController@vehicleTypes')->name('gen-vehicle-types');
Route::post('gen/veh/companies', 'GenerationController@vehicleCompanies')->name('gen-vehicle-companies');
Route::post('gen/veh/models', 'GenerationController@vehicleModels')->name('gen-vehicle-models');
Route::post('gen/veh/nature/material', 'GenerationController@vehicleMaterialNature')->name('gen-vehicle-nature-of-materials');
Route::post('booth/temp/pic', 'BoothController@getTempPics')->name('booth.temp.pic');
Route::post('booth/temp/pic/all', 'BoothController@getAllTempPics')->name('booth.temp.pic.all');


Route::post('generate_hrm_employee_type_with_ajax', 'HRM\EmployeeTypeController@generate_with_ajax');
Route::post('generate_hrm_employer_with_ajax', 'HRM\EmployerController@generate_with_ajax');
Route::post('generate_hrm_department_with_ajax', 'HRM\DepartmentController@generate_with_ajax');
Route::post('generate_hrm_designation_with_ajax', 'HRM\DesignationController@generate_with_ajax');
Route::post('generate_hrm_card_type_with_ajax', 'HRM\CardTypeController@generate_with_ajax');

Route::post('generate_relation_in_english_with_ajax', 'HRM\RelationController@generate_relation_in_english_with_ajax');
Route::post('generate_relation_in_urdu_with_ajax', 'HRM\RelationController@generate_relation_in_urdu_with_ajax');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Booth;
use App\Models\Device;
use App\Models\Log;
use App\Models\Notification;
use App\Models\Visitor;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $cLoginUser = Auth::user();
        if ($cLoginUser->hasDesignation('monitoring-cell-operator')) {
            $pageTitle = __('monitoring-cell.dashboard');
            $booths = Booth::join('gates', 'gates.id', 'booths.gate_id');
            if ($request->has('s') && $request->get('s') != '') {
                $keyword = $request->get('s', null);
                $booths = $booths->where(function ($q) use ($keyword) {
                    $q->where('booths.lane', 'like', '%' . $keyword . '%')
                        ->orWhere('booths.type', 'like', '%' . $keyword . '%')
                        ->orWhere('gates.name', 'like', '%' . $keyword . '%')
                        ->orWhere('gates.slug', 'like', '%' . $keyword . '%');
                });
            }
            if ($request->has('booth') && $request->get('booth') != '') {
                $filterBooth = $request->get('booth', null);
                $booths = $booths->where('booths.id', $filterBooth);
            }
            if ($request->has('gate') && $request->get('gate') != '') {
                $filterGate = $request->get('gate', null);
                $booths = $booths->where('gates.id', $filterGate);
            }
            $booths = $booths->select('booths.*', 'gates.name as gate')->get();
            $data = array();
            foreach ($booths as $booth) {
                $unreadNotifications = Notification::whereDate('created_at', Carbon::today())
                    ->where('data->booth_id', $booth->id)
                    ->whereNotifiableId(\auth()->user()->id)
                    ->whereReadAt(null)->count();
                $readNotifications = Notification::whereDate('created_at', Carbon::today())
                    ->where('data->booth_id', $booth->id)
                    ->whereNotifiableId(\auth()->user()->id)
                    ->where('read_at', '!=', null)->count();
                $data[$booth->id]['read'] = $readNotifications;
                $data[$booth->id]['unread'] = $unreadNotifications;
                $data[$booth->id]['visitors'] = Visitor::where('booth_id', $booth->id)->count();
                $data[$booth->id]['cameras'] = Device::where('booth_id', $booth->id)->count();
            }
            return view('monitoring-cell.dashboard', compact('pageTitle', 'data', 'booths'));
        } else {
            $pageTitle = __('dashboard.welcome_back_title');
            return view('dashboard.index', compact('pageTitle'));
        }
    }
}

resources/views/dashboard/boxes.blade.php
<div class="row">
    {{-- HRM --}}
    <div class="col-md-4">
        <div class="card card-widget widget-user">
            <div class="widget-user-header bg-gradient-success">
                <h4 class="widget-user-username ">{{__('hrm.heading')}}</h4>
            </div>
            <div class="widget-user-image">
                <img class="img-circle elevation-2" src="{{ asset('img/dashboard/hrm.png') }}" alt="HRM">
            </div>
            <div class="card-footer my-2">
                <div class="row ">
                    <div class="col-12 text-right">
                        @can('read',\App\Models\HRM::class)
                            <a href="{{ route('hrm.index') }}"
                               class="btn bg-gradient-success btn-sm">{{ __('system.manage') }} <i
                                    class="fa fa-arrow-circle-right"></i></a>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{-- VMS --}}
    <div class="col-md-4">
        <div class="card card-widget widget-user">
            <div class="widget-user-header bg-info">
                <h4 class="widget-user-username ">{{__('dashboard.visitor_management_system')}}</h4>
            </div>
            <div class="widget-user-image">
                <img class="img-circle elevation-2" src="{{ asset('img/dashboard/vms.jpg') }}" alt="VMS">
            </div>
            <div class="card-footer my-2">
                <div class="row ">
                    <div class="col-12 text-right">
                        @can('read',\App\Models\VMS::class)
                            <a href="{{ route('vms.index') }}"
                               class="btn bg-gradient-success btn-sm">{{ __('system.manage') }} <i
                                    class="fa fa-arrow-circle-right"></i></a>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{-- VRS --}}
    <div class="col-md-4">
        <div class="card card-widget widget-user">
            <div class="widget-user-header bg-gradient-danger">
                <h4 class="widget-user-username ">{{__('dashboard.vehicle_registration_system')}}</h4>
            </div>
            <div class="widget-user-image">
                <img class="img-circle elevation-2" src="{{ asset('img/dashboard/vehicle.png') }}" alt="VRS">
            </div>
            <div class="card-footer my-2">
                <div class="row ">
                    <div class="col-12 text-right">
                        @can('read',\App\Models\VRS::class)
                            <a href="{{ route('vrs.index') }}"
                               class="btn bg-gradient-success btn-sm">{{ __('system.manage') }} <i
                                    class="fa fa-arrow-circle-right"></i></a>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{--LRM--}}
    <div class="col-md-4">
        <div class="card card-widget widget-user">
            <div class="widget-user-header bg-gradient-info">
                <h4 class="widget-user-username ">{{__('dashboard.land_record_management_system')}}</h4>
            </div>
            <div class="widget-user-image">
                <img class="img-circle elevation-2" src="{{ asset('img/dashboard/lrm.png') }}" alt="LRM">
            </div>
            <div class="card-footer my-2">
                <div class="row ">
                    <div class="col-12 text-right">
                        @can('read',\App\Models\LRM::class)
                            <a href="{{ route('lrm.index') }}"
                               class="btn bg-gradient-success btn-sm">{{ __('system.manage') }} <i
                                    class="fa fa-arrow-circle-right"></i></a>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{--Device--}}
    <div class="col-md-4">
        <div class="card card-widget widget-user">
            <div class="widget-user-header bg-gradient-info">
                <h4 class="widget-user-username ">{{__('dashboard.device_management_system')}}</h4>
            </div>
            <div class="widget-user-image">
                <img class="img-circle elevation-2" src="{{ asset('img/dashboard/device.png') }}" alt="LRM">
            </div>
            <div class="card-footer my-2">
                <div class="row ">
                    <div class="col-12 text-right">
                        @can('read',\App\Models\Device::class)
                            <a href="{{ route('device.index') }}"
                               class="btn bg-gradient-success btn-sm">{{ __('system.manage') }} <i
                                    class="fa fa-arrow-circle-right"></i></a>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/dashboard/index.blade.php
@extends('layouts.dashboard')
@section('pageTitle', $pageTitle)
@section('content')
    @include('partials.dashboard.message')
    <div class="content">
        <div class="container-fluid">
           {{-- @include('dashboard.boxes') --}}
        </div>
    </div>
@endsection