routes/web.php
<?php

use App\Models\Role;
use App\Models\Permission;
use App\Models\User;
use App\Models\Setting;
use App\Models\Log;
use App\Models\Vehicle;
use App\Models\House;
use App\Models\Type;
use App\Models\Family;
use App\Models\FamilyPerson;
use App\Models\Camera;
use App\Models\VCompany;
use App\Models\VModel;

Auth::routes();

//auto redirect tp dashboard.....

Route::get('/', function () {

    return redirect('/dashboard/');

})->middleware('maintenance');

Route::group(['prefix' => '/dashboard', 'middleware' => ['maintenance']], function () {


    /* Country state city village dependent Drop Downs*/

    Route::resource('location', 'Location\HomeController');
    Route::resource('location-countries', 'Location\CountryController');
    Route::resource('location-states', 'Location\StateController');
    Route::resource('location-districts', 'Location\DistrictController');
    Route::resource('location-cities', 'Location\CityController');
    Route::resource('location-tehsils', 'Location\TehsilController');
    Route::resource('location-colonies', 'Location\ColonyController');

    /*Message Modules*/

    Route::resource('messages', 'MessageController');

    /*LRM (Land Record Management System*/

    Route::resource('lrm', 'LRM\HomeController');
    Route::resource('lrm-ministry', 'LRM\MinistryController');
    Route::resource('lrm-organization', 'LRM\OrganizationController');
    Route::resource('lrm-department', 'LRM\DepartmentController');
    Route::resource('lrm-rank', 'LRM\RankController');
    Route::resource('lrm-grade', 'LRM\GradeController');
    Route::resource('lrm-qualification', 'LRM\QualificationController');
    Route::resource('lrm-profession', 'LRM\ProfessionController');
    Route::resource('lrm-wing', 'LRM\WingController');
    Route::resource('lrm-settings', 'LRM\SettingController');
    /* Now ready to create Forms*/
    Route::resource('lrm-application', 'LRM\Form\ApplicationController');

    /*Device */

    Route::resource('device', 'Device\HomeController');
    Route::resource('device-class', 'Device\ClassController');
    Route::resource('device-operatingsystem', 'Device\DOperatingSystemController');
    Route::resource('device-make', 'Device\MakeController');
    Route::resource('device-model', 'Device\ModelController');
    Route::resource('device-type', 'Device\TypeController');

    /*VRS*/

    Route::resource('vrs', 'VRS\HomeController');
    Route::resource('vrs-vehicles', 'VRS\VehicleController');
    Route::resource('vrs-vehicle-types', 'VRS\VehicleTypeController');
    Route::resource('vrs-vehicle-companies', 'VRS\VehicleCompanyController');
    Route::resource('vrs-vehicle-models', 'VRS\VehicleModelController');
    Route::resource('vrs-vehicle-nature', 'VRS\VehicleNatureController');

    /*HRM*/

    Route::resource('hrm', 'HRM\HomeController');
    Route::resource('hrm-departments', 'HRM\DepartmentController');
    Route::resource('hrm-designations', 'HRM\DesignationController');
    Route::resource('hrm-employers', 'HRM\EmployerController');
    Route::resource('hrm-emp-types', 'HRM\EmployeeTypeController');
    Route::resource('hrm-card-types', 'HRM\CardTypeController');
    Route::resource('hrm-relations', 'HRM\RelationController');

    /*....Society Phases and Gates....*/

    Route::resource('society-gates', 'Society\GateController');
    Route::resource('society-booths', 'Society\BoothController');
    Route::resource('society-phase-gate-locations', 'Society\LocationController');


    /*visitor companies*/

    Route::resource('vcompanies', 'Vehicle\CompanyController');

    /*visitor models*/

    Route::resource('vmodels', 'Vehicle\ModelController');

    Route::get('', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);

    Route::get('system/apply/status/{type}/{id}/{value}', ['as' => 'system.apply.status', 'uses' => 'System\AjaxController@apply_status']);
    //Load more routes
    Route::get('system/load/more/{type}', ['as' => 'system.load.more', 'uses' => 'System\AjaxController@load_more']);
    //System Assigning routes
    Route::post('system/assign', ['as' => 'system.assign', 'uses' => 'System\AjaxController@assign']);

    Route::get('till', ['as' => 'till', 'uses' => 'TillController@index',
        'permissions' => User::modulePermissions(true, 'read')]);
    Route::get('tills/logs', ['as' => 'tills.logs', 'uses' => 'TillController@logs']);
    Route::get('till/manage', ['as' => 'till.manage', 'uses' => 'TillController@index',
        'permissions' => \App\Models\Booth::modulePermissions(true, 'read')]);

    //Settings

    Route::get('settings', ['as' => 'settings', 'uses' => 'SettingController@index',
        'permissions' => Setting::modulePermissions(true, 'read')]);
    Route::put('settings/update/{id}', ['as' => 'settings.update', 'uses' => 'SettingController@update',
        'permissions' => Setting::modulePermissions(true, 'edit')]);

    //Logs

    Route::get('logs/{type?}', ['as' => 'logs', 'uses' => 'LogController@index',
        'permissions' => Log::modulePermissions(true, 'read')]);

    //Applying status
    Route::get('system/apply/status/{type}/{id}/{value}', ['as' => 'system.apply.status', 'uses' => 'System\AjaxController@apply_status']);
    //Load more routes
    Route::get('system/load/more/{type}', ['as' => 'system.load.more', 'uses' => 'System\AjaxController@load_more']);
    //System Assigning routes
    Route::post('system/assign', ['as' => 'system.assign', 'uses' => 'System\AjaxController@assign']);


    // List of all Notifications

    Route::get('booth-notifications-count', 'BoothController@countNotifications')->name('booth-notifications-count');
    Route::get('booth-notifications/{for}/{type}/{boothId}', 'BoothController@getNotifications')->name('booth-notifications');
    Route::post('booth-read-notifications', 'BoothController@markAsReadNotifications')->name('booth-read-notifications');
    Route::get('booth-visitor-logs/{boothId}', 'BoothController@visitorLog')->name('booth-visitor-logs');
    Route::get('booth-cameras/{boothId}', 'BoothController@boothCameras')->name('booth-cameras');
    Route::get('booth-images/{boothId}', 'BoothController@boothImages')->name('booth-images');
    // Manage Visitor

    Route::resource('visitors', 'VisitorController');

});


Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\LoginController@logout']);
Route::get('lang/{locale}', 'SwitcherController@lang')->name('lang.switcher')->middleware('maintenance');
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login')->middleware('maintenance');
Route::post('customLogin', 'Auth\LoginController@customLogin')->name('customLogin')->middleware('maintenance');
Route::post('customBoothLogin', 'Auth\BoothController@customBoothLogin')->name('customBoothLogin');
Route::get('boothLogin', 'Auth\BoothController@login')->name('booth.login');
Route::get('/till/filter', 'TillController@filter')->name('till.filter');
Route::get('/logs/visitor/set', 'LogController@save_visitor_logs')->name('till.filter');
Route::post('till/visitor/save', 'TillController@save_visitor')->name('till.visitor.save');
Route::post('/till/visitor/logs', 'VisitorController@save_logs')->name('till.visitor.save');
Route::post('/dependent/dropdown', 'DropDownController@filter');
Route::get('booth', 'BoothController@manage')->name('booth.manage')->middleware('boothLogin');


Route::post('booth/logout', 'Auth\BoothController@logout')->name('booth.logout');

Route::post('booth/visitors/enter', 'BoothController@enter')->name('booth-enter-visitor');
Route::post('booth/visitors/exit', 'BoothController@exit')->name('booth-exit-visitor');
Route::get('booth/visitor-already-enter-not-exit', 'BoothController@alreadyEnterNotExit')->name('visitor-already-enter-not-exit');
Route::post('booth/visitor/check/exit', 'BoothController@checkVisitorAtExit')->name('booth-check-visitor-at-exit');
Route::post('booth/visitor/check/enter', 'BoothController@checkVisitorAtEnter')->name('booth-check-visitor-at-enter');
Route::post('gen/veh/types', 'GenerationController@vehicleTypes')->name('gen-vehicle-types');
Route::post('gen/veh/companies', 'GenerationController@vehicleCompanies')->name('gen-vehicle-companies');
Route::post('gen/veh/models', 'GenerationController@vehicleModels')->name('gen-vehicle-models');
Route::post('gen/veh/nature/material', 'GenerationController@vehicleMaterialNature')->name('gen-vehicle-nature-of-materials');
Route::post('booth/temp/pic', 'BoothController@getTempPics')->name('booth.temp.pic');
Route::post('booth/temp/pic/all', 'BoothController@getAllTempPics')->name('booth.temp.pic.all');


Route::post('generate_hrm_employee_type_with_ajax', 'HRM\EmployeeTypeController@generate_with_ajax');
Route::post('generate_hrm_employer_with_ajax', 'HRM\EmployerController@generate_with_ajax');
Route::post('generate_hrm_department_with_ajax', 'HRM\DepartmentController@generate_with_ajax');
Route::post('generate_hrm_designation_with_ajax', 'HRM\DesignationController@generate_with_ajax');
Route::post('generate_hrm_card_type_with_ajax', 'HRM\CardTypeController@generate_with_ajax');

Route::post('generate_relation_in_english_with_ajax', 'HRM\RelationController@generate_relation_in_english_with_ajax');
Route::post('generate_relation_in_urdu_with_ajax', 'HRM\RelationController@generate_relation_in_urdu_with_ajax');

app/Http/Controllers/Device/TypeController.php
<?php

namespace App\Http\Controllers\Device;

use App\Http\Controllers\Controller;
use App\Models\Device;
use App\Models\Employer;
use App\Device\DType;
use App\Repositories\CurdRepository;
use Carbon\Carbon;
use Illuminate\Http\Request;

class TypeController extends Controller
{
    protected $model;

    public function __construct(DType $DType)
    {
        $this->middleware('auth');
        // set the model
        $this->model = new CurdRepository($DType);
    }

    public function index(Request $request)
    {
        $this->authorize('read', Device::class);
        $data = $this->model->all($request->all());
        $pageTitle = __('device.all_types');
        $viewParams = [
            'pageTitle' => $pageTitle,
            'data' => $data->paginate(20)
        ];
        return view('device.type.index', $viewParams);
    }

    public function create(Request $request)
    {
        $this->authorize('create', Device::class);
        $pageTitle = __('device.create_new_type');
        $viewParams = [
            'pageTitle' => $pageTitle,
        ];
        return view('device.type.create', $viewParams);
    }

    public function store(Request $request)
    {
        $this->authorize('create', Device::class);
        $request->validate([
            'name' => 'required|max:255|unique:dtypes,name',
            'name_ur' => 'max:255|unique:dtypes,name_ur',
        ]);
        if ($this->model->create($request->only($this->model->getModel()->fillable))) {
            return redirect()->route('device-type.index')->with('successMessage', __('device.type_created_success_message'));
        }
    }

    public function edit($id)
    {
        $this->authorize('edit', Device::class);
        $this->model = $this->model->find($id);
        $pageTitle = __('device.edit') . $this->model->name;
        $viewParams = [
            'pageTitle' => $pageTitle,
            'model' => $this->model,
        ];
        return view('device.type.edit', $viewParams);

    }

    public function update(Request $request,$id)
    {
        $request->validate([
            'name' => 'required|max:255|unique:dtypes,name,' . $id,
            'name_ur' => 'unique:dtypes,name,' . $id,
        ]);
        $this->authorize('edit', Device::class);
        $this->model->update($request->only($this->model->getModel()->fillable), $id);
        $this->model = $this->model->find($id);
        if ($this->model) {
            return redirect()->route('device-type.index')->with('successMessage', $this->model->name . " " . __('device.updated_success_message'));
        }
    }

    public function destroy($id)
    {
        $this->authorize('delete', Device::class);
        $this->model = $this->model->find($id);
        if ($this->model->delete($id)) {
            return redirect()->route('device-type.index')->with('errorMessage', $this->model->name . " " . __('device.deleted_successfully'));
        }
    }
}

app/Http/Controllers/System/AjaxController.php
<?php

namespace App\Http\Controllers\System;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AjaxController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/system/types/create.blade.php
@extends('layouts.dashboard')
@section('pageTitle', $pageTitle)

@section('styleInnerFiles')
    <link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
@endsection

@section('breadcrumbs')
    @include('partials.dashboard.breadcrumbs', ['pageTitle' => $pageTitle,'breadcrumbs' => $breadcrumbs])
@stop

@section('content')
    <div class="card card-solid">
        @can('read',\App\Models\Type::class)
            <div class="card-header">
                <div class="card-title">
                    {!! link_to_route('system.types',__('system.master_tables'),[$parent],['class'=>'btn btn-info btn-sm']) !!}
                </div>
            </div>
        @endcan
        <div class="card-body pb-0">
            <!-- form start -->
            {!! Form::open(['route' => ['system.types.store',$parent], 'method' => 'POST']) !!}
            {!! csrf_field() !!}
            @include('partials.dashboard.message')
            <div class="form-group">
                {!! Form::label('name', __('system.name')) !!}
                {!! Form::text('name', null, ['class' => 'form-control', 'required', 'autofocus','placeholder'=>__('system.placeholder_name'), 'id' => 'name','onkeyup'=>'Custom.replaceSpaceWithHypen(this)' ]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('label', __('system.label')) !!}
                {!! Form::text('label', null, ['class' => 'form-control', 'required', 'id' => 'label','placeholder'=>__('system.placeholder_label'),'onkeyup'=>'Custom.upperCaseEveryLetter(this)' ]) !!}
            </div>
            <div class="form-group text-right">
                {!! Form::submit(__('system.save'), array('class' => 'btn btn-primary btn-sm')) !!}
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@stop

resources/views/system/types/index.blade.php
@extends('layouts.dashboard')
@section('pageTitle', $pageTitle)

@section('breadcrumbs')
    @include('partials.dashboard.breadcrumbs', ['pageTitle' => $pageTitle,'breadcrumbs' => $breadcrumbs])
@stop
@inject('edBlade','App\Repositories\EdBlade')
@section('content')
    <div class="timeline">
        @php $counter=1;  @endphp
        @foreach($data as $parent=>$value)
            <div>
                <i class="fa bg-gradient-success">{{ $counter++ }}</i>
                <div class="timeline-item align-items-center">
                    <a class="time badge badge-info text-white" style="padding: 6px;margin: 7px;"
                       href="{{ route('system.types.create',[$parent]) }}">
                        {{ __('system.create')." ".$parent }}
                    </a>
                    <h1 class="timeline-header font-weight-bold"> {{ ucfirst(str_replace('-',' ',$parent)) }}</h1>
                    <div class="timeline-body">
                        @foreach($value as $inner_key=>$type)
                            <div class="btn btn-app">
                                {{ $type->label }}
                                @if($parent=='vehicle')
                                    {!! link_to_route('vcompanies.index',__('system.companies'),["type_id"=>$type->id],['class'=>'time badge badge-success text-white']) !!} ({{\App\Models\VCompany::where('type_id',$type->id)->count()}})
                                @endif
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@stop